# =============================
# = Spring
# =============================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.cdwfvmgkmgff.us-east-2.rds.amazonaws.com:3306/bluemeet?serverTimezone=UTC&useSSL=false
    username: admin